version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
 vmImage:windows-latest
      name: win/default 
      size: "medium" 
 
    steps:
      -checkout:none
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "Password2017"
            Set-Variable -Name "NGROK" -Value "1sWG9b0AnwU36zqoR1SpiblgFG1_4DJRgqrC3vzYyvHmHVdWc"
            Invoke-WebRequest https://raw.githubusercontent.com/Fiate/WINDOWSRDP/main/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1